#ifndef RECIPE_COLLECTION_MENU_H
#define RECIPE_COLLECTION_MENU_H
enum menu {
    ALL_RECIPES,
    CREATE_RECIPE,
    DELETE_RECIPE,
    SEARCH_BY_RECIPE,
    SEARCH_BY_INGREDIENT,
    HELP
};
#endif //RECIPE_COLLECTION_MENU_H
